"""SCHEMA와 마이그레이션 대상(TABLES) 목록이 항상 일치하는지 검증.

SCHEMA(db.py)와 TABLES(db_migrate.py)가 이중 관리되던 시절, 테이블을 SCHEMA에만
추가하고 TABLES에 반영하는 걸 잊으면 마이그레이션에서 조용히 데이터가 누락됐다.
지금은 TABLES가 SCHEMA에서 자동 파생되지만, 이 테스트는 SCHEMA를 별도 정규식으로
직접 훑어서 TABLES와 대조한다 — 파생 로직 자체가 깨지거나 TABLES가 다시 수기로
바뀌어도 즉시 실패하도록.
"""
import re
from store.db import SCHEMA
from store.db_migrate import TABLES


def test_migration_tables_cover_every_schema_table():
    schema_tables = set(re.findall(r"create table if not exists (\w+)\(", SCHEMA, re.IGNORECASE))
    assert set(TABLES) == schema_tables


def test_migration_tables_have_columns():
    assert TABLES
    for name, cols in TABLES.items():
        assert cols, f"{name}: 복사할 컬럼이 없음"


def test_migration_tables_exclude_autogenerated_columns():
    # autoincrement / default current_timestamp 컬럼은 대상 DB가 새로 채번·찍어야 하므로 제외돼야 함
    for cols in TABLES.values():
        assert "id" not in cols
        assert "created" not in cols
        assert "generated" not in cols
